name: easy_thermal_print
description: "a package for accessing thermal printers via flutter"
version: 0.1.3+2
homepage: https://pub.dev/packages/easy_thermal_print
repository: https://github.com/RobinNaumann/easy_thermal_print
topics:
  - bluetooth
  - ble
  - thermal printer
  - printing
  - phomemo
  - thermalprint
  - halftone

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
